import sys, json, duckdb, numpy as np, pandas as pd
A = sys.argv[1]; L = sys.argv[2]
con = duckdb.connect(); con.execute("LOAD spatial")
con.execute(f"CREATE VIEW b AS SELECT * EXCLUDE (geometry) FROM read_parquet('{A}/buildings_12103.parquet')")
con.execute(f"CREATE VIEW p AS SELECT * FROM read_parquet('{A}/parcels_12103.parquet')")
con.execute(f"CREATE VIEW f AS SELECT * FROM read_parquet('{L}/features.parquet')")
def q(s): return con.execute(s).df()
pd.set_option("display.width", 250); pd.set_option("display.max_columns", 40)
print("== ground_ft sentinel check ==")
print(q("SELECT ground_ft, count(*) n FROM b WHERE ground_ft IS NOT NULL GROUP BY 1 ORDER BY 2 DESC LIMIT 8"))
print(q("SELECT count(*) n_lt_m199, sum(CASE WHEN ffh_class='modeled' THEN 1 ELSE 0 END) modeled, sum(CASE WHEN touches_sfha THEN 1 ELSE 0 END) sfha, sum(CASE WHEN bfe_call='below' THEN 1 ELSE 0 END) below, sum(CASE WHEN bfe_call='too_close' THEN 1 ELSE 0 END) too_close, sum(CASE WHEN bfe_call='above' THEN 1 ELSE 0 END) above FROM b WHERE ground_ft < -1.99"))
print(q("SELECT ground_status, count(*) n, min(g_lag) mn, quantile_cont(g_lag,0.001) p01, sum(CASE WHEN g_lag < -1.99 THEN 1 ELSE 0 END) lt_m199, sum(CASE WHEN g_lag <= -1.9998 AND g_lag >= -2.0 THEN 1 ELSE 0 END) at_sentinel FROM f GROUP BY 1"))
print("features g_* for the sentinel rows:")
print(q("SELECT b.building_id, round(b.ground_ft,3) ground, round(f.g_p10,2) g_p10, round(f.g_med,2) g_med, round(f.g_hag,2) g_hag, round(f.g_inside,2) g_inside, round(f.g_far,2) g_far, f.n_in, b.zone_main, b.bfe_ft, round(b.ffh_ft,2) ffh, round(b.ffe_ft,2) ffe, b.bfe_call, b.ffh_class FROM b JOIN f USING (building_id) WHERE b.ground_ft < -1.99 ORDER BY b.ground_ft LIMIT 12"))
print("ground < 0 by whether g_med - g_lag large (water in ring?):")
print(q("SELECT CASE WHEN ground_ft < -1.99 THEN 'sentinel' WHEN ground_ft < 0 THEN 'neg' WHEN ground_ft < 1 THEN '0-1' ELSE '>=1' END grp, count(*) n, round(median(f.g_med - f.g_lag),2) med_gmed_minus_lag, round(median(f.g_inside - f.g_lag),2) med_ginside_minus_lag, round(avg(CASE WHEN bfe_call='below' THEN 1 ELSE 0 END),3) below_share, round(avg(CASE WHEN ffh_class='modeled' THEN 1 ELSE 0 END),3) modeled_share FROM b JOIN f USING (building_id) WHERE ground_ft IS NOT NULL GROUP BY 1 ORDER BY 1"))
print("g_inside - g_lag (ring min vs inside) for modeled, distribution:")
print(q("SELECT quantile_cont(f.g_inside - f.g_lag, [0.01,0.05,0.5,0.95,0.99]) FROM b JOIN f USING (building_id) WHERE ffh_class='modeled'"))
print("modeled buildings where ring min is > 3 ft below the inside ground (likely seawall/water in ring):")
print(q("SELECT count(*) n, sum(CASE WHEN touches_sfha THEN 1 ELSE 0 END) sfha, sum(CASE WHEN bfe_call='below' THEN 1 ELSE 0 END) below, sum(CASE WHEN bfe_call='too_close' THEN 1 ELSE 0 END) tc, sum(CASE WHEN bfe_call='above' THEN 1 ELSE 0 END) above FROM b JOIN f USING (building_id) WHERE ffh_class='modeled' AND f.g_inside - f.g_lag > 3"))
print("== static BFE > 30 vs ground ==")
print(q("SELECT bfe_ft, count(*) n, round(median(ground_ft),1) med_ground, round(min(ground_ft),1) min_ground, round(max(ground_ft),1) max_ground, sum(CASE WHEN bfe_call='below' THEN 1 ELSE 0 END) below, sum(CASE WHEN bfe_call='above' THEN 1 ELSE 0 END) above, string_agg(DISTINCT zone_main, ',') zones FROM b WHERE bfe_method='static' AND bfe_ft > 30 GROUP BY 1 ORDER BY 1"))
print(q("SELECT round(median(bfe_ft-ground_ft),2) med_bfe_minus_ground, quantile_cont(bfe_ft-ground_ft,[0.01,0.1,0.5,0.9,0.99]) qs, sum(CASE WHEN bfe_ft-ground_ft > 15 THEN 1 ELSE 0 END) gt15, sum(CASE WHEN bfe_ft-ground_ft < -10 THEN 1 ELSE 0 END) lt_m10, count(*) n FROM b WHERE bfe_method='static' AND ground_ft IS NOT NULL"))
print("static BFE minus ground > 10 ft (BFE far above the ground: a datum/zone error signature or deep floodway):")
print(q("SELECT zone_main, bfe_ft, count(*) n, round(median(ground_ft),1) med_ground, sum(CASE WHEN bfe_call='below' THEN 1 ELSE 0 END) below, string_agg(DISTINCT bfe_vintage, ',') v FROM b WHERE bfe_method='static' AND bfe_ft-ground_ft > 10 GROUP BY 1,2 ORDER BY 3 DESC LIMIT 12"))
print("interpolated BFE > 30 vs ground:")
print(q("SELECT count(*) n, round(median(bfe_ft-ground_ft),2) med_diff, min(bfe_ft-ground_ft) mn, max(bfe_ft-ground_ft) mx FROM b WHERE bfe_method='interpolated' AND bfe_ft>30 AND ground_ft IS NOT NULL"))
print(q("SELECT quantile_cont(bfe_ft-ground_ft,[0.01,0.1,0.5,0.9,0.99]) qs, sum(CASE WHEN bfe_ft-ground_ft > 15 THEN 1 ELSE 0 END) gt15, sum(CASE WHEN bfe_ft-ground_ft < -10 THEN 1 ELSE 0 END) lt_m10 FROM b WHERE bfe_method='interpolated' AND ground_ft IS NOT NULL"))
print("interpolated: source line text sample where bfe - ground > 15:")
print(q("SELECT building_id, round(bfe_ft,2) bfe, round(ground_ft,2) ground, zone_main, bfe_call, left(bfe_source, 160) src FROM b WHERE bfe_method='interpolated' AND bfe_ft-ground_ft > 15 ORDER BY bfe_ft-ground_ft DESC LIMIT 5").to_string())
print("== parcel table ==")
print(q("SELECT parcel_key, count(*) n FROM p GROUP BY 1 HAVING count(*)>1 ORDER BY 2 DESC LIMIT 5"))
print(q("SELECT count(DISTINCT parcel_key) dup_keys, sum(n) rows FROM (SELECT parcel_key, count(*) n FROM p GROUP BY 1 HAVING count(*)>1)"))
print(q("SELECT a.parcel_key, a.geom_group, a.dor_uc, a.buildings, a.below, a.primary_building_id = b2.primary_building_id same_prim FROM p a JOIN p b2 USING (parcel_key) WHERE a.geom_group <> b2.geom_group LIMIT 6"))
print("geom_group sizes (parcels sharing one polygon):")
print(q("SELECT geom_group, count(*) parcels, max(buildings) buildings, max(below) below FROM p GROUP BY 1 ORDER BY 2 DESC LIMIT 8"))
print(q("SELECT quantile_cont(n, [0.5,0.9,0.99,0.999]) parcels_per_group, max(n) mx FROM (SELECT geom_group, count(*) n FROM p GROUP BY 1)"))
print(q("SELECT max(buildings) max_buildings_on_parcel, quantile_cont(buildings,[0.5,0.99]) q FROM p"))
print("parcels with buildings > 50:")
print(q("SELECT count(*) FROM p WHERE buildings > 50"))
print("== record rows: cert LAG vs lidar ground discrepancy vs conflict flag ==")
print(q("""SELECT CASE WHEN abs((ffe_ft-ground_ft)-ffh_ft) > 3 THEN 'lag_vs_lidar_gt3' ELSE 'le3' END grp, ffe_record_lidar_conflict conflict, count(*) n,
  sum(CASE WHEN bfe_call='above' THEN 1 ELSE 0 END) above, sum(CASE WHEN bfe_call='below' THEN 1 ELSE 0 END) below FROM b WHERE ffh_class='record' AND ground_ft IS NOT NULL GROUP BY 1,2 ORDER BY 1,2"""))
print("record rows where cert LAG is > 3 ft ABOVE lidar ground (cert says ground higher):")
print(q("SELECT count(*) n, round(median(ffe_ft-ground_ft),2) med_ffe_minus_lidar_ground, round(median(ffh_ft),2) med_ffh_record FROM b WHERE ffh_class='record' AND ground_ft IS NOT NULL AND (ffe_ft-ground_ft)-ffh_ft > 3"))
print("== record calls with ffe exactly at BFE: 74 -> above; within 0.5 ft of BFE: ==")
print(q("SELECT bfe_call, count(*) n FROM b WHERE ffe_class='record' AND bfe_method='static' AND abs(ffe_ft-bfe_ft) <= 0.5 GROUP BY 1"))
print("== modeled 'above' with floor_minus_bfe < 1 ==")
print(q("SELECT count(*) n, round(median(ffe_band_lo-bfe_ft),3) med_margin, min(ffe_band_lo-bfe_ft) mn FROM b WHERE bfe_call='above' AND ffe_class='modeled' AND floor_minus_bfe_ft < 1"))
print("== modeled band width > 20 ft; max band rows ==")
print(q("SELECT building_id, round(ffh_ft,2) ffh, round(ffh_band_lo,2) lo, round(ffh_band_hi,2) hi, round(roof_ft,1) roof, round(footprint_area_m2) area, dor_use_code, bfe_call FROM b WHERE ffh_class='modeled' ORDER BY ffh_band_hi-ffh_band_lo DESC LIMIT 5"))
print(q("SELECT sum(CASE WHEN ffh_band_hi-ffh_band_lo>20 THEN 1 ELSE 0 END) gt20, sum(CASE WHEN ffh_band_lo < -1 THEN 1 ELSE 0 END) lo_below_m1, sum(CASE WHEN ffh_band_hi > roof_ft THEN 1 ELSE 0 END) hi_above_roof FROM b WHERE ffh_class='modeled'"))
print("== living_area > 50k on modeled rows (condo totals used as a feature?) ==")
print(q("SELECT dor_use_code, count(*) n, round(median(living_area_sqft)) med_la, round(median(footprint_area_m2)) med_fp FROM b WHERE ffh_class='modeled' AND living_area_sqft > 50000 GROUP BY 1 ORDER BY 2 DESC LIMIT 5"))
print(q("SELECT count(*) n_modeled_la_gt50k FROM b WHERE ffh_class='modeled' AND living_area_sqft > 50000"))
print("== zone list anomalies: 'A' zone buildings with static bfe (4) ==")
print(q("SELECT building_id, zones, bfe_ft, bfe_source FROM b WHERE zone_main='A' AND bfe_method='static' LIMIT 4").to_string())
print("== X zone_main with bfe (5,461): sfha_share ==")
print(q("SELECT quantile_cont(sfha_share,[0.1,0.5,0.9]) q, count(*) n, sum(CASE WHEN bfe_call='below' THEN 1 ELSE 0 END) below FROM b WHERE zone_main='X' AND bfe_ft IS NOT NULL"))
print("== below calls by sfha_share band (sliver sensitivity) ==")
print(q("SELECT CASE WHEN sfha_share<0.01 THEN '<1%' WHEN sfha_share<0.1 THEN '1-10%' WHEN sfha_share<0.5 THEN '10-50%' ELSE '>=50%' END band, count(*) n, sum(CASE WHEN bfe_call='below' THEN 1 ELSE 0 END) below, sum(CASE WHEN bfe_call='above' THEN 1 ELSE 0 END) above, sum(CASE WHEN bfe_call='too_close' THEN 1 ELSE 0 END) tc FROM b WHERE touches_sfha GROUP BY 1 ORDER BY 1"))
