exec(open("backtest.py").read().split("lat=np.radians")[0])
import duckdb, pyarrow as pa
df=pa.Table.from_pylist([{k:r[k] for k in ["OBJECTID","propertyId","streetAddress","zipcode","nfipCommunityNumber","floodZone","baseFloodElevation","topOfBottomFloor","lowestAdjacentGrade","highestAdjacentGrade","buildingDiagramNumber","issuedAt","lon","lat"]} for r in D])
c=duckdb.connect("tmp_join.duckdb"); c.execute("LOAD spatial; LOAD h3; SET threads=4; SET memory_limit='6GB'; SET preserve_insertion_order=false")
c.register("ec_df",df); c.execute("CREATE OR REPLACE TABLE ec AS SELECT *, floor(lon*100)::INT gx, floor(lat*100)::INT gy FROM ec_df")
c.execute("""CREATE OR REPLACE TABLE pb AS SELECT row_id, bbox.xmin x0, bbox.ymin y0, bbox.xmax x1, bbox.ymax y1 FROM read_parquet('fl_parcels.parquet')""")
# expand each parcel bbox to grid buckets (parcels larger than ~5 buckets skipped from bucketing -> handled via fallback)
c.execute("""CREATE OR REPLACE TABLE pg AS SELECT row_id, x0,y0,x1,y1, gx, gy FROM pb,
  generate_series(floor(x0*100)::INT, floor(x1*100)::INT) t1(gx), generate_series(floor(y0*100)::INT, floor(y1*100)::INT) t2(gy)
  WHERE (floor(x1*100)-floor(x0*100)+1)*(floor(y1*100)-floor(y0*100)+1) <= 25""")
c.execute("""CREATE OR REPLACE TABLE cand AS SELECT e.OBJECTID, g.row_id FROM ec e JOIN pg g USING (gx,gy) WHERE e.lon BETWEEN g.x0 AND g.x1 AND e.lat BETWEEN g.y0 AND g.y1""")
print("candidates",c.execute("select count(*), count(distinct OBJECTID) from cand").fetchone())
c.execute("""CREATE OR REPLACE TABLE pc AS SELECT p.row_id, p.county_fips, p.parcel_id, p.dor_uc, p.act_yr_blt, p.eff_yr_blt, p.tot_lvg_ar, p.no_buldng, p.no_res_unt, p.jv, p.lnd_sqfoot, p.geom
  FROM read_parquet('fl_parcels.parquet') p SEMI JOIN (SELECT DISTINCT row_id FROM cand) c USING (row_id)""")
c.execute("""CREATE OR REPLACE TABLE j AS SELECT c.OBJECTID, p.* EXCLUDE (geom) FROM cand c JOIN pc p USING (row_id) JOIN ec e USING (OBJECTID)
  WHERE ST_Intersects(p.geom, ST_Point(e.lon,e.lat)) QUALIFY row_number() OVER (PARTITION BY c.OBJECTID ORDER BY p.act_yr_blt DESC NULLS LAST)=1""")
print("joined",c.execute("select count(*) from j").fetchone())
c.execute("COPY (SELECT e.* EXCLUDE (gx,gy), j.* EXCLUDE (OBJECTID,row_id) FROM ec e LEFT JOIN j USING (OBJECTID)) TO 'ec_joined.parquet'")
# neighbourhood population: single-family parcels whose label cell lies in the certificates' r8 cells (+1 ring)
c.execute("CREATE OR REPLACE TABLE cells AS SELECT DISTINCT unnest(h3_grid_disk(h3_latlng_to_cell(lat,lon,8),1)) AS c FROM ec")
c.execute("""COPY (SELECT act_yr_blt FROM read_parquet('fl_parcels.parquet') WHERE dor_uc='0001' AND h3_cell_to_parent(h3_index,8) IN (SELECT c FROM cells)) TO 'pop_years.parquet'""")
print("pop",c.execute("select count(*) from 'pop_years.parquet'").fetchone())
